/*

 MAZEMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : D:\Bonner\Documents\Jacob Bonner\Homework\ICS3U\Saved Programs\GameBoy Sprites\mazesprites.gbr
   Plane count   : 0.5 plane (4 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define mazemapWidth 20
#define mazemapHeight 18
#define mazemapBank 0

extern unsigned char mazemap[];

/* End of MAZEMAP.H */
